INFO     [2019-10-27 15:34:15,913] POST
INFO     [2019-10-27 15:34:15,950] 200 OK
INFO     [2019-10-27 15:34:15,956] DELETE
INFO     [2019-10-27 15:34:15,998] DELETE
WARNING  [2019-10-27 15:34:16,014] 404 Not found
INFO     [2019-10-27 15:34:16,031] POST
INFO     [2019-10-27 15:34:16,069] 200 OK
INFO     [2019-10-27 15:34:16,081] GET
INFO     [2019-10-27 15:34:16,103] DELETE
INFO     [2019-10-27 15:34:16,173] GET
WARNING  [2019-10-27 15:34:16,195] 404 Not found
INFO     [2019-10-27 15:34:16,206] POST
INFO     [2019-10-27 15:34:16,249] 200 OK
INFO     [2019-10-27 15:34:16,258] DELETE
INFO     [2019-10-27 15:34:16,302] POST
WARNING  [2019-10-27 15:34:16,303] 400 Body not valid
INFO     [2019-10-27 15:34:16,309] POST
INFO     [2019-10-27 15:34:16,354] 200 OK
INFO     [2019-10-27 15:34:16,362] POST
WARNING  [2019-10-27 15:34:16,382] 409 Key exists
INFO     [2019-10-27 15:34:16,392] DELETE
INFO     [2019-10-27 15:34:16,434] POST
INFO     [2019-10-27 15:34:16,475] 200 OK
INFO     [2019-10-27 15:34:16,483] PUT
INFO     [2019-10-27 15:34:16,528] DELETE
INFO     [2019-10-27 15:34:16,588] PUT
WARNING  [2019-10-27 15:34:16,588] 400 Body not valid
INFO     [2019-10-27 15:34:16,596] PUT
WARNING  [2019-10-27 15:34:16,622] 404 Not found
INFO     [2019-10-27 17:25:10,518] POST
ERROR    [2019-10-27 17:25:10,549] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:10,679] DELETE
ERROR    [2019-10-27 17:25:10,702] Internal Server Error: /kv/opposite/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 101, in another
    if not get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:10,853] DELETE
ERROR    [2019-10-27 17:25:10,872] Internal Server Error: /kv/putin/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 101, in another
    if not get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:10,998] POST
ERROR    [2019-10-27 17:25:11,019] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,131] GET
ERROR    [2019-10-27 17:25:11,148] Internal Server Error: /kv/money/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 91, in another
    response = get_value_by_key(key)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,253] GET
ERROR    [2019-10-27 17:25:11,270] Internal Server Error: /kv/ukrainian_crimea/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 91, in another
    response = get_value_by_key(key)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,385] POST
ERROR    [2019-10-27 17:25:11,404] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,518] POST
WARNING  [2019-10-27 17:25:11,518] 400 Body not valid
INFO     [2019-10-27 17:25:11,532] POST
ERROR    [2019-10-27 17:25:11,554] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,662] POST
ERROR    [2019-10-27 17:25:11,676] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,782] POST
ERROR    [2019-10-27 17:25:11,802] Internal Server Error: /kv/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 60, in post
    if get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:11,907] PUT
ERROR    [2019-10-27 17:25:11,932] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 82, in another
    if not get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:25:12,037] PUT
WARNING  [2019-10-27 17:25:12,037] 400 Body not valid
INFO     [2019-10-27 17:25:12,045] PUT
ERROR    [2019-10-27 17:25:12,070] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 82, in another
    if not get_value_by_key(key):
  File "/home/s/MAI/ML/tarantool/storage/storage/views.py", line 20, in get_value_by_key
    value = list(c.select("KVStorage", key))
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/connection.py", line 761, in select
    space_name = self.schema.get_space(space_name).sid
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 86, in get_space
    return self.fetch_space(space)
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/tarantool/schema.py", line 100, in fetch_space
    raise SchemaError(errmsg)
tarantool.error.SchemaError: There's no space with name 'KVStorage'
INFO     [2019-10-27 17:27:52,590] POST
INFO     [2019-10-27 17:27:52,619] 200 OK
INFO     [2019-10-27 17:27:52,628] DELETE
INFO     [2019-10-27 17:27:52,669] DELETE
WARNING  [2019-10-27 17:27:52,687] 404 Not found
INFO     [2019-10-27 17:27:52,698] POST
INFO     [2019-10-27 17:27:52,731] 200 OK
INFO     [2019-10-27 17:27:52,740] GET
INFO     [2019-10-27 17:27:52,764] DELETE
INFO     [2019-10-27 17:27:52,810] GET
WARNING  [2019-10-27 17:27:52,829] 404 Not found
INFO     [2019-10-27 17:27:52,841] POST
INFO     [2019-10-27 17:27:52,874] 200 OK
INFO     [2019-10-27 17:27:52,882] DELETE
INFO     [2019-10-27 17:27:52,925] POST
WARNING  [2019-10-27 17:27:52,926] 400 Body not valid
INFO     [2019-10-27 17:27:52,934] POST
INFO     [2019-10-27 17:27:52,976] 200 OK
INFO     [2019-10-27 17:27:52,983] POST
WARNING  [2019-10-27 17:27:52,998] 409 Key exists
INFO     [2019-10-27 17:27:53,009] DELETE
INFO     [2019-10-27 17:27:53,051] POST
INFO     [2019-10-27 17:27:53,088] 200 OK
INFO     [2019-10-27 17:27:53,095] PUT
ERROR    [2019-10-27 17:27:53,129] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:27:53,186] PUT
WARNING  [2019-10-27 17:27:53,186] 400 Body not valid
INFO     [2019-10-27 17:27:53,191] PUT
ERROR    [2019-10-27 17:27:53,220] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:31:11,341] POST
INFO     [2019-10-27 17:31:11,371] 200 OK
INFO     [2019-10-27 17:31:11,383] DELETE
INFO     [2019-10-27 17:31:11,423] DELETE
WARNING  [2019-10-27 17:31:11,438] 404 Not found
INFO     [2019-10-27 17:31:11,451] POST
INFO     [2019-10-27 17:31:11,481] 200 OK
INFO     [2019-10-27 17:31:11,488] GET
INFO     [2019-10-27 17:31:11,537] DELETE
INFO     [2019-10-27 17:31:11,585] GET
WARNING  [2019-10-27 17:31:11,601] 404 Not found
INFO     [2019-10-27 17:31:11,612] POST
WARNING  [2019-10-27 17:31:11,630] 409 Key exists
INFO     [2019-10-27 17:31:11,647] POST
WARNING  [2019-10-27 17:31:11,648] 400 Body not valid
INFO     [2019-10-27 17:31:11,656] POST
WARNING  [2019-10-27 17:31:11,678] 409 Key exists
INFO     [2019-10-27 17:31:11,685] POST
WARNING  [2019-10-27 17:31:11,707] 409 Key exists
INFO     [2019-10-27 17:31:11,715] DELETE
INFO     [2019-10-27 17:31:11,761] POST
INFO     [2019-10-27 17:31:11,798] 200 OK
INFO     [2019-10-27 17:31:11,806] PUT
ERROR    [2019-10-27 17:31:11,842] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:31:11,912] PUT
WARNING  [2019-10-27 17:31:11,912] 400 Body not valid
INFO     [2019-10-27 17:31:11,919] PUT
ERROR    [2019-10-27 17:31:11,962] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:33:31,080] POST
INFO     [2019-10-27 17:33:31,112] 200 OK
INFO     [2019-10-27 17:33:31,126] DELETE
INFO     [2019-10-27 17:33:31,161] DELETE
WARNING  [2019-10-27 17:33:31,178] 404 Not found
INFO     [2019-10-27 17:33:31,189] POST
INFO     [2019-10-27 17:33:31,223] 200 OK
INFO     [2019-10-27 17:33:31,229] GET
INFO     [2019-10-27 17:33:31,274] DELETE
INFO     [2019-10-27 17:33:31,313] GET
WARNING  [2019-10-27 17:33:31,332] 404 Not found
INFO     [2019-10-27 17:33:31,343] POST
WARNING  [2019-10-27 17:33:31,365] 409 Key exists
INFO     [2019-10-27 17:33:31,382] POST
WARNING  [2019-10-27 17:33:31,383] 400 Body not valid
INFO     [2019-10-27 17:33:31,392] POST
WARNING  [2019-10-27 17:33:31,413] 409 Key exists
INFO     [2019-10-27 17:33:31,424] POST
WARNING  [2019-10-27 17:33:31,444] 409 Key exists
INFO     [2019-10-27 17:33:31,453] DELETE
INFO     [2019-10-27 17:33:31,502] POST
INFO     [2019-10-27 17:33:31,544] 200 OK
INFO     [2019-10-27 17:33:31,552] PUT
ERROR    [2019-10-27 17:33:31,588] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:33:31,662] PUT
WARNING  [2019-10-27 17:33:31,662] 400 Body not valid
INFO     [2019-10-27 17:33:31,667] PUT
ERROR    [2019-10-27 17:33:31,700] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:36:37,221] POST
INFO     [2019-10-27 17:36:37,253] 200 OK
INFO     [2019-10-27 17:36:37,263] DELETE
INFO     [2019-10-27 17:36:37,301] DELETE
WARNING  [2019-10-27 17:36:37,316] 404 Not found
INFO     [2019-10-27 17:36:37,328] POST
INFO     [2019-10-27 17:36:37,362] 200 OK
INFO     [2019-10-27 17:36:37,369] GET
INFO     [2019-10-27 17:36:37,400] DELETE
INFO     [2019-10-27 17:36:37,460] GET
WARNING  [2019-10-27 17:36:37,473] 404 Not found
INFO     [2019-10-27 17:36:37,484] POST
INFO     [2019-10-27 17:36:37,520] 200 OK
INFO     [2019-10-27 17:36:37,527] DELETE
INFO     [2019-10-27 17:36:37,568] POST
WARNING  [2019-10-27 17:36:37,568] 400 Body not valid
INFO     [2019-10-27 17:36:37,574] POST
INFO     [2019-10-27 17:36:37,612] 200 OK
INFO     [2019-10-27 17:36:37,619] POST
WARNING  [2019-10-27 17:36:37,636] 409 Key exists
INFO     [2019-10-27 17:36:37,643] DELETE
INFO     [2019-10-27 17:36:37,683] POST
INFO     [2019-10-27 17:36:37,723] 200 OK
INFO     [2019-10-27 17:36:37,731] PUT
ERROR    [2019-10-27 17:36:37,768] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:36:37,832] PUT
WARNING  [2019-10-27 17:36:37,832] 400 Body not valid
INFO     [2019-10-27 17:36:37,837] PUT
ERROR    [2019-10-27 17:36:37,870] Internal Server Error: /kv/president/
Traceback (most recent call last):
  File "/home/s/MAI/ML/tarantool/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view storage.views.another didn't return an HttpResponse object. It returned None instead.
INFO     [2019-10-27 17:38:49,129] POST
INFO     [2019-10-27 17:38:49,161] 200 OK
INFO     [2019-10-27 17:38:49,174] DELETE
INFO     [2019-10-27 17:38:49,213] DELETE
WARNING  [2019-10-27 17:38:49,226] 404 Not found
INFO     [2019-10-27 17:38:49,242] POST
INFO     [2019-10-27 17:38:49,275] 200 OK
INFO     [2019-10-27 17:38:49,282] GET
INFO     [2019-10-27 17:38:49,325] DELETE
INFO     [2019-10-27 17:38:49,363] GET
WARNING  [2019-10-27 17:38:49,380] 404 Not found
INFO     [2019-10-27 17:38:49,393] POST
WARNING  [2019-10-27 17:38:49,411] 409 Key exists
INFO     [2019-10-27 17:38:49,420] POST
WARNING  [2019-10-27 17:38:49,420] 400 Body not valid
INFO     [2019-10-27 17:38:49,427] POST
WARNING  [2019-10-27 17:38:49,451] 409 Key exists
INFO     [2019-10-27 17:38:49,458] POST
WARNING  [2019-10-27 17:38:49,478] 409 Key exists
INFO     [2019-10-27 17:38:49,487] DELETE
INFO     [2019-10-27 17:38:49,535] POST
INFO     [2019-10-27 17:38:49,567] 200 OK
INFO     [2019-10-27 17:38:49,577] PUT
INFO     [2019-10-27 17:38:49,619] DELETE
INFO     [2019-10-27 17:38:49,659] PUT
WARNING  [2019-10-27 17:38:49,659] 400 Body not valid
INFO     [2019-10-27 17:38:49,664] PUT
WARNING  [2019-10-27 17:38:49,687] 404 Not found
INFO     [2019-10-27 17:40:16,040] POST
INFO     [2019-10-27 17:40:16,069] 200 OK
INFO     [2019-10-27 17:40:16,080] DELETE
INFO     [2019-10-27 17:40:16,120] DELETE
WARNING  [2019-10-27 17:40:16,135] 404 Not found
INFO     [2019-10-27 17:40:16,145] POST
INFO     [2019-10-27 17:40:16,179] 200 OK
INFO     [2019-10-27 17:40:16,190] GET
INFO     [2019-10-27 17:40:16,217] DELETE
INFO     [2019-10-27 17:40:16,277] GET
WARNING  [2019-10-27 17:40:16,292] 404 Not found
INFO     [2019-10-27 17:40:16,306] POST
INFO     [2019-10-27 17:40:16,339] 200 OK
INFO     [2019-10-27 17:40:16,346] DELETE
INFO     [2019-10-27 17:40:16,384] POST
WARNING  [2019-10-27 17:40:16,384] 400 Body not valid
INFO     [2019-10-27 17:40:16,391] POST
INFO     [2019-10-27 17:40:16,428] 200 OK
INFO     [2019-10-27 17:40:16,435] POST
WARNING  [2019-10-27 17:40:16,450] 409 Key exists
INFO     [2019-10-27 17:40:16,462] DELETE
INFO     [2019-10-27 17:40:16,502] POST
INFO     [2019-10-27 17:40:16,535] 200 OK
INFO     [2019-10-27 17:40:16,542] PUT
INFO     [2019-10-27 17:40:16,583] DELETE
INFO     [2019-10-27 17:40:16,631] PUT
WARNING  [2019-10-27 17:40:16,631] 400 Body not valid
INFO     [2019-10-27 17:40:16,643] PUT
WARNING  [2019-10-27 17:40:16,668] 404 Not found
INFO     [2019-10-27 17:40:20,164] POST
INFO     [2019-10-27 17:40:20,194] 200 OK
INFO     [2019-10-27 17:40:20,207] DELETE
INFO     [2019-10-27 17:40:20,248] DELETE
WARNING  [2019-10-27 17:40:20,265] 404 Not found
INFO     [2019-10-27 17:40:20,276] POST
INFO     [2019-10-27 17:40:20,315] 200 OK
INFO     [2019-10-27 17:40:20,322] GET
INFO     [2019-10-27 17:40:20,353] DELETE
INFO     [2019-10-27 17:40:20,393] GET
WARNING  [2019-10-27 17:40:20,411] 404 Not found
INFO     [2019-10-27 17:40:20,429] POST
INFO     [2019-10-27 17:40:20,462] 200 OK
INFO     [2019-10-27 17:40:20,470] DELETE
INFO     [2019-10-27 17:40:20,509] POST
WARNING  [2019-10-27 17:40:20,510] 400 Body not valid
INFO     [2019-10-27 17:40:20,515] POST
INFO     [2019-10-27 17:40:20,557] 200 OK
INFO     [2019-10-27 17:40:20,569] POST
WARNING  [2019-10-27 17:40:20,584] 409 Key exists
INFO     [2019-10-27 17:40:20,595] DELETE
INFO     [2019-10-27 17:40:20,636] POST
INFO     [2019-10-27 17:40:20,670] 200 OK
INFO     [2019-10-27 17:40:20,677] PUT
INFO     [2019-10-27 17:40:20,721] DELETE
INFO     [2019-10-27 17:40:20,765] PUT
WARNING  [2019-10-27 17:40:20,765] 400 Body not valid
INFO     [2019-10-27 17:40:20,775] PUT
WARNING  [2019-10-27 17:40:20,798] 404 Not found
